CREATE TABLE expenses (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    title VARCHAR NOT NULL,
    description VARCHAR,
    timestamp DATETIME NOT NULL,
    value_decimal INTEGER NOT NULL
)